let suggestions = [
    "Exploiting Auxiliary Data for Offensive Language Detection with Bidirectional Transformers",
    "Proceedings of the 5th Workshop on Online Abuse and Harms (WOAH 2021)",
    "Findings of the {WOAH} 5 Shared Task on Fine Grained Hateful Memes Detection",
    "Abusive Language on Social Media Through the Legal Looking Glass",
    "Targets and Aspects in Social Media Hate Speech",
    "When the Echo Chamber Shatters: Examining the Use of Community-Specific Language Post-Subreddit Ban",
    "Data Integration for Toxic Comment Classification: Making More Than 40 Datasets Easily Accessible in One Unified Format",
    "A Large-Scale {E}nglish Multi-Label {T}witter Dataset for Cyberbullying and Online Abuse Detection",
    "Context Sensitivity Estimation in Toxicity Detection",
    "Fine-grained Classification of Political Bias in {G}erman News: A Data Set and Initial Experiments",
    "Jibes {\&} Delights: A Dataset of Targeted Insults and Compliments to Tackle Online Abuse",
    "Mitigating Biases in Toxic Language Detection through Invariant Rationalization",
    "Hell Hath No Fury? Correcting Bias in the {NRC} Emotion Lexicon",
    "Improving Counterfactual Generation for Fair Hate Speech Detection",
    "Fine-Grained Fairness Analysis of Abusive Language Detection Systems with {C}heck{L}ist",
    "Offensive Language Detection in {N}epali Social Media",
    "{DALC}: the {D}utch Abusive Language Corpus",
    "Measuring and Improving Model-Moderator Collaboration using Uncertainty Estimation",
    "Memes in the Wild: Assessing the Generalizability of the Hateful Memes Challenge Dataset",
    "{H}ate{BERT}: Retraining {BERT} for Abusive Language Detection in {E}nglish",
    "Modeling Profanity and Hate Speech in Social Media with Semantic Subspaces",
];
